### ISSUE TITLE
how to run this code?

### ISSUE THREAD

**Issue by uragan1987** [openlgtv/lh_lgmod#1]
hi, this hook looks great
but how you compile it and how to run on lg?
i have webos 4.5 with only "prisoner" user, is it enough?

**Comment by smx-smx** [comment]
Hello
This code requires libhooker (https://github.com/smx-smx/libhooker). You add the modules in the `modules` folder and add them to CMakeLists.txt

You can use the toolchain included in the GPL release, or otherwise one that is compatible with the Linux and glibc versions of your TV.

As for running the code, you need root access to inject code in the RELEASE/tvservice process.

**Comment by uragan1987** [comment]
well done, thx
